A = imread('Abdullah.jpg');
B = imread('Abdullah.jpg');
C = imread('Abdullah.jpg');
D = imread('Abdullah.jpg');
subplot(3,4,1);imshow(A); title('Image 1');
A = rgb2gray(A);
subplot(3,4,2);imhist(A);title(' Histogram of Image 1');
subplot(3,4,3);imshow(B); title('Image 2');
B = rgb2gray(B);
subplot(3,4,4);imhist(B);title(' Histogram of Image 2');
subplot(3,4,5);imshow(C); title('Image 3');
C = rgb2gray(C);
subplot(3,4,6);imhist(C);title(' Histogram of Image 3');
subplot(3,4,7);imshow(D); title('Image 4');
D = rgb2gray(D);
subplot(3,4,8);imhist(D);title('Histogram of Image 4');
E = [A,B;C,D];
subplot(3,4,10);imshow(E); title('Marge Image');
subplot(3,4,11);imhist(E);title('Histogram of Marge Image');